class RouteNames {
  RouteNames._();

  static const String splash = '/splash';
  static const String login = '/login';
  static const String otpVerification = '/otp-verification';
  static const String onboardingEmail = '/onboarding/email';
  static const String onboardingPhone = '/onboarding/phone';
  static const String onboardingProfile = '/onboarding/profile';
  static const String onboardingGender = '/onboarding/gender';
  static const String onboardingLocation = '/onboarding/location';
  static const String home = '/home';
  static const String chat = '/home/chat';
  static const String chatAnnouncement = '/home/chat/announcement';
  static const String chatPostDetail = '/home/chat/announcement/post';
  static const String chatPublicGroup = '/home/chat/public';
  static const String chatGroupInfo = '/home/chat/group-info';
  static const String concierge = '/home/concierge';
  static const String editProfile = '/profile/edit';
  static const String profilePicture = '/profile/picture';
  static const String residencyIdentification = '/profile/residency';
  static const String familyMembers = '/profile/family-members';
  static const String editFamilyMember = '/profile/family-members/edit';
  static const String properties = '/profile/properties';
  static const String editProperty = '/profile/properties/edit';
  static const String vehicles = '/profile/vehicles';
  static const String editVehicle = '/profile/vehicles/edit';
  static const String pets = '/profile/pets';
  static const String editPet = '/profile/pets/edit';
  static const String residencyTerms = '/profile/residency-terms';
  static const String mainHome = '/main-home';
  static const String propertyDetail = '/main-home/property-detail';
  static const String invoicePayment = '/main-home/invoice-payment';
  static const String billingAccount = '/main-home/billing-account';
  static const String payment = '/main-home/payment';
  static const String bankTransaction = '/main-home/payment/bank-transaction';
  static const String serviceProfile = '/main-home/service-profile';
  static const String adminAccountModification = '/main-home/property-detail/admin-account-modification';
  static const String accountTermination = '/main-home/property-detail/account-termination';
}
